# Generated by Django 4.2.4 on 2023-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pgxpipeline_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_created=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=190)),
                ('total_time', models.CharField(max_length=150)),
            ],
        ),
    ]
