# Generated by Django 4.2.4 on 2023-08-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgxpipelineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pgxpipeline_bam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bamfile', models.FileField(upload_to='')),
                ('vcf_file', models.FileField(upload_to='')),
                ('refrence_file', models.FileField(upload_to='')),
                ('bed_file', models.FileField(upload_to='')),
                ('patient_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='pgxpipeline_log',
            name='end_time',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pgxpipeline_log',
            name='start_time',
            field=models.CharField(max_length=150),
        ),
    ]
