# Generated by Django 4.2.4 on 2023-08-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgxpipelineapp', '0002_pgxpipeline_bam_alter_pgxpipeline_log_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgxpipeline_log',
            name='end_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pgxpipeline_log',
            name='total_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
