# Generated by Django 4.2.4 on 2023-08-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgxpipelineapp', '0004_alter_pgxpipeline_log_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgxpipeline_bam',
            name='bamfile',
        ),
        migrations.RemoveField(
            model_name='pgxpipeline_bam',
            name='bed_file',
        ),
        migrations.RemoveField(
            model_name='pgxpipeline_bam',
            name='refrence_file',
        ),
        migrations.RemoveField(
            model_name='pgxpipeline_bam',
            name='vcf_file',
        ),
        migrations.AddField(
            model_name='pgxpipeline_bam',
            name='bamfile_path',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgxpipeline_bam',
            name='bed_path',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgxpipeline_bam',
            name='refrence_path',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgxpipeline_bam',
            name='vcf_file_path',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgxpipeline_log',
            name='patient_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pgxpipelineapp.pgxpipeline_bam'),
            preserve_default=False,
        ),
    ]
