# Generated by Django 4.2.4 on 2023-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgxpipelineapp', '0006_rename_refrence_path_pgxpipeline_bam_results_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgxpipeline_bam',
            name='patient_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
